#ifndef GUIDS_H
#define GUIDS_H

#include <BLEUUID.h>
#include <WString.h>

class UUIDs
{
public:

    static const BLEUUID UUID_SCRIPT_SERVICE;
    static const BLEUUID UUID_HELMET_SERVICE;
    static const BLEUUID UUID_CHEST_SERVICE;
    static const BLEUUID UUID_BACK_SERVICE;
    static const BLEUUID UUID_RIGHT_ARM_SERVICE;
    static const BLEUUID UUID_LEFT_ARM_SERVICE;
    static const BLEUUID UUID_RIGHT_LEG_SERVICE;
    static const BLEUUID UUID_LEFT_LEG_SERVICE;

    static const BLEUUID UUID_DEFAULTS_SCRIPT_CHARACTERISTIC;
    static const BLEUUID UUID_THREAT_DISPLAY_SCRIPT_CHARACTERISTIC;
    static const BLEUUID UUID_ANGRY_SCRIPT_CHARACTERISTIC;
    static const BLEUUID UUID_READY_TO_FLY_SCRIPT_CHARACTERISTIC;
    static const BLEUUID UUID_FLAPS_TEST_SCRIPT_CHARACTERISTIC;

    static const BLEUUID UUID_EYES_CHARACTERISTIC;
    static const BLEUUID UUID_FACEPLATE_CHARACTERISTIC;
    static const BLEUUID UUID_SPEECH_CHARACTERISTIC;

    static const BLEUUID UUID_ARC_REACTOR_CHARACTERISTIC;
    static const BLEUUID UUID_CHEST_FLAPS_CHARACTERISTIC;

    static const BLEUUID UUID_BACK_FLAPS_CHARACTERISTIC;

    static const BLEUUID UUID_RIGHT_ARM_LASER_CHARACTERISTIC;
    static const BLEUUID UUID_RIGHT_ARM_ROCKET_CHARACTERISTIC;
    static const BLEUUID UUID_RIGHT_ARM_REPULSOR_CHARACTERISTIC;

    static const BLEUUID UUID_LEFT_ARM_LASER_CHARACTERISTIC;
    static const BLEUUID UUID_LEFT_ARM_ROCKET_CHARACTERISTIC;
    static const BLEUUID UUID_LEFT_ARM_REPULSOR_CHARACTERISTIC;

    static const BLEUUID UUID_RIGHT_LEG_FLAPS_CHARACTERISTIC;

    static const BLEUUID UUID_LEFT_LEG_FLAPS_CHARACTERISTIC;
    
    static String nameOf(const BLEUUID &uuid);
};

#endif // GUIDS_H
